### ISSUE TITLE
Unexpectedly found nil

### ISSUE THREAD

**Issue by d7laungani** [joehour/LocationKit#2]
When I use this code

```
  let location: LocationManager = LocationManager()
  var geocoder = CLGeocoder()


location.getLocation(detectStyle: .Once, completion: { (loc) in
                self.currentLocation = loc.currentLocation
                geocoder.reverseGeocodeLocation(loc.currentLocation, completionHandler: { (placemarks, error) in
                    let placemark = placemarks?.first
                    self.locationLabel.text = placemark?.addressDictionary?["Street"] as! String?
                    
                })
                
                
            }, error: { (error) in
                print(error)
            }
            )

```
It asks for location and then it crashes saying

Failure to deallocate CLLocationManager on the same runloop as its creation may result in a crash
fatal error: unexpectedly found nil while unwrapping an Optional value

The line it crashes in on your library is File LOcationDetection.swift

 if detectionItem.detectStyle != .SignificantLocationChanges {
                        if detectionItem.detectStyle == .Once {
              ->>>>              detectionItem.lcoationDetection.locationManager.stopUpdatingLocation()

I debugged it and it seems that locationManager is nil and so it cannot stopUpdatingLocation on a nil instance. Any help?

**Comment by joehour** [comment]
Hi,
I've already fixed this issue.
I think this issue is the stopUpdatingLocation function of locationManager doesn't work immediately
You can find the fix code in [LocationDetection.swift](https://github.com/joehour/LocationKit/blob/master/LocationKit/LocationDetection.swift#L309)

**Comment by d7laungani** [comment]
Thank you !
